// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzsnngobsxthviccaiye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6c25uZ29ic3h0aHZpY2NhaXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMTI0MjAsImV4cCI6MjA2Nzg4ODQyMH0.6IV46elBewjatxySLq_0-_BnB5pXSe7ZW_0uc7GAsXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});